# Generated by Django 4.2.7 on 2023-12-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basee', '0003_alter_room_options_rename_uptaded_room_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='uptaded',
            new_name='updated',
        ),
    ]
